### ISSUE TITLE
i get an error when i try to do npm i

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/reborn-example-plugin#1]
# npm resolution error report

While resolving: reborn-example-plugin@1.0.0
Found: webpack@5.88.2
node_modules/webpack
  dev webpack@"^5.88.2" from the root project

Could not resolve dependency:
peer webpack@"^4.0.0" from uglifyjs-webpack-plugin@2.2.0
node_modules/uglifyjs-webpack-plugin
  dev uglifyjs-webpack-plugin@"^2.2.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by leahanderson1** [comment]
do npm i --force

**Comment by leahanderson1** [comment]
can i close this?

**Comment by radmanplays** [comment]
> can i close this?

yes

**Comment by leahanderson1** [comment]
now 100% fixed
